### ISSUE TITLE
[BE] Investigate file uploads

### ISSUE THREAD

**Issue by katsukixyz** [GTBitsOfGood/angels-among-us#23]
## Context

In later sprints, we want to implement the ability for content creators and admins to attach images and videos to posts. We want to find out what calls we need to make to our storage bucket API in order to implement this functionality.

## Requirements

We will use Backblaze B2 for our file storage. Reference their documentation ([https://www.backblaze.com/b2/docs/calling.html](https://www.backblaze.com/b2/docs/calling.html)) to see how we can pipeline files to the storage bucket. Reference [https://stackoverflow.com/questions/33279153/rest-api-file-ie-images-processing-best-practices](https://stackoverflow.com/questions/33279153/rest-api-file-ie-images-processing-best-practices) for best practices (passing the data to backend then to Backblaze or data straight to Backblaze?) You are free to start building out this flow if you’d like, but it's not a requirement for the completion of this ticket.

The scope of this ticket is rather large - consider tackling this across both Sprint 2 and 3. We won’t need this functionality immediately, so work on your other assigned tickets before diving into this one.

## Acceptance Criteria

- [ ]  Identify key milestones to build out in order to make file uploads a reality
    - [ ]  Write down what API keys/secrets we need to store on our end
- [ ]  Find out how we can ensure that when a post is deleted, all its corresponding files be removed from the bucket as well (is the link to the file enough or do we need to store some other data?)
- [ ]  Identify what limits we should set on file uploads to minimize HTTP issues when we transfer the data across APIs

**Comment by tmthecoder** [comment]
## **Everything in this post is open to comment, leave any feedback. Once finalized, this will act as the guide for an implementation**

### File Uploads 

#### Key Assumptions

- We will be using this for primarily images
- Backblaze B2 is the preferred storage backend
- Images are going to be loaded in a large number (to populate a feed with many posts, each potentially with multiple images)

#### Backblaze B2

- Backblaze B2 provides low-cost storage with minimal charges for transactions, storage, and egress.
- They offer bucket access through two different APIs: their own ([docs](https://www.backblaze.com/b2/docs/)) and an S3 Compatible API ([docs](https://www.backblaze.com/b2/docs/s3_compatible_api.html))
- Both APIs come with their set of perks and drawbacks

#### B2: Native API
- The native API is Backblaze's own API, built for interaction with their storage service and access key management
- It allows key and identity management through the API (allowing us to create user-specific keys)
    - This may be of minimal (or essential) use to us depending on our chosen method of implementation
- It also allows for server-side authorizations for downloads and file change operations (We can create a server endpoint to get and return an authorized token scoped to a file download/upload) with a single master key, hence why the above isn't too useful
- However, we need to request upload URLs from the API (which may change from time to time, returning a 503 error in which another round trip is needed to request a new URL
- Not many open source clients exist to wrap functionality, requiring a lot of manual boilerplate for setup and error handling

#### B2: S3 API
- The S3 API follows general industry standards (set by S3), providing a uniform API that can be used across various other storage providers also implement
- There are countless open source clients to implement API functionality (wrapping many operations and boilerplate)
- No identity and key management exists (server would have to validate request callers and return appropriate results)
    - The server can create a predesigned URL for downloads and uploads (similar to providing the authorized downloads and uploads for specific items in the native API)
- Upload URL is static: We won't need to worry about the upload URL logic

#### Extra Considerations
- Both clients still will occasionally return 503 error indicating a file cannot currently be uploaded and must be tried again. I'm unsure about the frequency of this
- Since this is used in lower write, primarily read buckets (images are uploaded once, viewed many more times on a feed), some cache would be extremely useful in performance (see [here](https://help.backblaze.com/hc/en-us/articles/360010017893-Delivering-Backblaze-B2-Content-Through-Cloudflare-CDN)). The service is free and reduces the egress cost.

#### Deletion
- To delete an item from the bucket we'd need its path in the bucket. Instead of storing the URL in MongoDB, I suggest that only the path be stored.
    -  The full URL can be constructed from the path (just prepend the domain and bucket prefix)
    - The path fragment will allow us to store less info and directly pass it to a deletion call

#### Compression/Resizing
- It may be worth storing compressed copies of images in some cases (depending on how we want to show images in some cases)
    - For example, if we want to show images that are smaller sized, we don't have to pull a full-sized image and can instead pull a much smaller compressed or resized image, reducing pull bandwidth and increasing overall speed on the user's side. 
- Depending on the compression and sizes needed, this may or may not be a hit on the actual storage used (as duplicates of images may be stored)
- We can also set maximum sizes for images (or auto-resize down) as it's highly unlikely we'd need the full quality of some images users will upload (4K, etc)
    - Storage-saving and performance boosting (pulls are smaller and thus shorter)
 
#### Implementation Plan (WIP)
- Configure a B2 bucket with Cloudflare (might need the use of CF workers)
- Use the S3 API with a JS/TS client to abstract many of the manual requests
- Upload/download items from the client directly (don't send through server)
    - The main reason is the bandwidth save. This is an iffy decision as it could harm UX sometimes
    - We can call an authorize request to our server (which will validate the request and provide a presigned URL for the upload/download operation)
    - Use that URL with the S3 client to upload/download the file(s) in question
- For uploads:
    - Client/FE calls a server-side (our API) `validate_upload` endpoint and a presigned URL is returned
    - Client/FE proceeds to upload file using presigned URL
    - On success, client calls an update to the post info (adding the path of the updated file to the attachments list)
- For downloads: 
    -  Feed viewers call downloads for each image loaded on the feed (Client/FE)
        - This can be an authenticated call if we make buckets private (and then require a download authorization call per-file)
        - Depending on the choice of compression/resizing, parameters/postfixes can be added to retrieve a smaller image if we store multiple copies at different sizes
- Limits:
    - I'm not sure any limits need to be set as we can probably dynamically resize images
        - Shrink/convert format to something smaller if it ends up being too high-resolution (not sure of the exact point, maybe 2000p+? )
     - If not, we can check for file sizes and request users upload smaller images, but that might be more of a UX hit than auto-resizing

**Comment by katsukixyz** [comment]
Thanks for the writeup! Your implementation plan looks good - just wondering about the details on how image resizing would work. In terms of the scope of this feature - do you think it can be done in 1 sprint (Sprint 3)?

**Comment by tmthecoder** [comment]
@katsukixyz I think it's definitely feasible to finish up in one sprint, but it'll definitely be a heavier load than any ticket I've seen currently assigned.

About image resizing, we can use [sharp](https://www.npmjs.com/package/sharp) if we setup a backend endpoint to do it, or look into client side resize options (I've done it with JS before, it wasn't too bad from what I remember)

**Comment by katsukixyz** [comment]
@tmthecoder would you be comfortable taking this on for next sprint? The scope would be everything we've discussed so far.

Your call on client/server-side for image resizing, would the UX hit for a file size limit outweigh the work needed to resize images on FE/BE? Side note I'm also pretty confident we can make the Cloudflare CDN work with Backblaze.

**Comment by tmthecoder** [comment]
@katsukixyz I can probably take this on. I'll probably work on it mainly through the week of the 26th since I have a rough week next week. Do you want me to handle just the server-side authorization + upload logic and someone else tackles the frontend portion (uploading with the returned presigned URL) in a subsequent sprint?

In terms of the image resizing, I was thinking we check the size on client and if it's too large we resize and upload from server, but all pulls will be done client side again.

**Comment by katsukixyz** [comment]
@tmthecoder Image resizing plan sounds good! The scope of the ticket will be the authorization, upload logic, and any resizing work that is involved with that. This is a pretty massive ticket, so don't worry if it takes you longer than 1 sprint to get it done. The frontend will be a completely different ticket, but during testing if you want to make a test page where you can iterate using a frontend, you're welcome to do that.

**Comment by tmthecoder** [comment]
@katsukixyz Sounds good to me. Will you be setting up the backblaze account and env configuration for keys or should I handle some component of that?

**Comment by katsukixyz** [comment]
@tmthecoder I'll set up an account and provide you the credentials so you can work on it freely!
